apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-eventos-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: eventos.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ms-eventos
                port:
                  number: 80