apiVersion: v1
kind: Pod
metadata:
  name: oracle-xe
  labels:
    app: oracle-xe
spec:
  containers:
    - name: oracle-xe
      image: gvenzl/oracle-xe:18.4.0-slim
      ports:
        - containerPort: 1521
      env:
        - name: ORACLE_PASSWORD
          value: admin
      volumeMounts:
        - mountPath: /opt/oracle/oradata
          name: oracle-data
  volumes:
    - name: oracle-data
      emptyDir: {} 
