apiVersion: v1
kind: Service
metadata:
  name: ms-gateway
  labels:
    app: ms-gateway
spec:
  type: LoadBalancer
  selector:
    app: ms-gateway
  ports:
    - name: http
      protocol: TCP
      port: 9099
      targetPort: 9099
      nodePort: 30099

