apiVersion: v1
kind: Service
metadata:
  name: ms-participantes
spec:
  selector:
    app: ms-participantes
  ports:
  - protocol: TCP
    port: 9084
    targetPort: 9084
    nodePort: 30084
  type: NodePort
