apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-eventos
  labels:
    app: ms-eventos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-eventos
  template:
    metadata:
      labels:
        app: ms-eventos
    spec:
      containers:
        - name: ms-eventos
          image: jbalboar/ms-eventos:2.0
          args:
            - "--spring.config.additional-location=file:/config/"
          ports:
            - containerPort: 9081

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9081
            initialDelaySeconds: 100
            periodSeconds: 30
            timeoutSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9081
            initialDelaySeconds: 105
            periodSeconds: 10
            timeoutSeconds: 10

          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

          resources:
            requests:
              cpu: "100m"
              memory: "400Mi"
            limits:
              cpu: "200m"
              memory: "600Mi"

          volumeMounts:
            - name: config-volume
              mountPath: /config/
              subPath: application.yml
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: ms-eventos-config
            items:
              - key: application.yml
                path: application.yml

