ALTER SESSION SET CONTAINER = XEPDB1;
CREATE USER g4user IDENTIFIED BY g4password
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

GRANT CONNECT, RESOURCE TO g4user;
ALTER USER g4user QUOTA UNLIMITED ON users;

ALTER USER g4user QUOTA UNLIMITED ON users;