apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-gateway-config
  namespace: default
data:
  application.yml: |
    spring:
      application:
        name: ms-gateway
      cloud:
        gateway:
          routes:
            - id: ms-eventos
              uri: lb://ms-eventos
              predicates:
                - Path=/api1/**
              filters:
                - StripPrefix=1
            - id: ms-participantes
              uri: lb://ms-participantes
              predicates:
                - Path=/api2/**
              filters:
                - RewritePath=/api2/(?<segment>.*), /$\{segment}
    server:
      port: 9099

